### ISSUE TITLE
Print coverage result after finish `allDebugCoverage` task

### ISSUE THREAD

**Issue by trietbui85** [thsaravana/jacoco-android-playground#4]
I notice in https://github.com/alisonthemonster/Presently/blob/develop/gradle/jacoco_ci.gradle , there is a quite interesting task `printReport` which will print coverage result. For example:
```
- instruction coverage rate is 28.23%
- line coverage rate is 25.36%
- method coverage rate is 39.28%
- class coverage rate is 35.46%
```

Would you mind to integrate it to your Jacoco script too?

**Comment by thsaravana** [comment]
I don't think this is required.
This repository is to act as a project for testing `jacoco-report` action. Adding this `printReport` will just print the coverage info in the workflow run logs, which I don't think is an add-on for this repository.
